### ISSUE TITLE
Move user guide out of the README

### ISSUE THREAD

**Issue by romifz** [open-contracting/toucan#92]
#90 adds new user guidance for Toucan in the README files. However, @aguilerapy and I discussed that it may be best to have guidance in a separate document, which we can link in Toucan's landing page, and leave the README files for technical instructions only.

Is it possible to have a separate documentation site, like the Kingfisher modules?  Or would it be best to use a public Google Doc? @jpmckinney

**Comment by jpmckinney** [comment]
Do you mean specifically the "Use examples"? https://github.com/Cristobal961/toucan#use-examples?

For a tool like Toucan, in general, I think it's best for user guidance to be integrated into the tool itself.

Do you think those examples are necessary? I think the tools are fairly easy to understand. If people are having a hard time understanding the tools, instead of writing instructions, I think it's better to focus on improving the UI.

**Comment by romifz** [comment]
Providing examples was a suggestion from @juanpane. I think you're right, there is not much to explain about the use of the tools.

Examples are useful for OCDS beginners. So perhaps we can move these to a Google Doc and keep it as a learning content.

**Comment by yolile** [comment]
closed by #120
